//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizeResourcesChinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeResourcesChinese() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizeResourcesChinese", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ActiveDate {
            get {
                return ResourceManager.GetString("ActiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警报数量.
        /// </summary>
        internal static string AlertQty {
            get {
                return ResourceManager.GetString("AlertQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 量.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量单位.
        /// </summary>
        internal static string AmountUnit {
            get {
                return ResourceManager.GetString("AmountUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用中心.
        /// </summary>
        internal static string ApplicationCenter {
            get {
                return ResourceManager.GetString("ApplicationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资产管理.
        /// </summary>
        internal static string AssetManagement {
            get {
                return ResourceManager.GetString("AssetManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BoilingPoint {
            get {
                return ResourceManager.GetString("BoilingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务归档.
        /// </summary>
        internal static string BusinessArchiving {
            get {
                return ResourceManager.GetString("BusinessArchiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务系统.
        /// </summary>
        internal static string BusinessSystem {
            get {
                return ResourceManager.GetString("BusinessSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目录#.
        /// </summary>
        internal static string Catalog_ {
            get {
                return ResourceManager.GetString("Catalog#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类别.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 证书接收.
        /// </summary>
        internal static string CertificateReception {
            get {
                return ResourceManager.GetString("CertificateReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 证书发放.
        /// </summary>
        internal static string CertificateRelease {
            get {
                return ResourceManager.GetString("CertificateRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ClauseSubject {
            get {
                return ResourceManager.GetString("ClauseSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础配置.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户管理.
        /// </summary>
        internal static string CustomerManagement {
            get {
                return ResourceManager.GetString("CustomerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理看板.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DaysSampleKeeping {
            get {
                return ResourceManager.GetString("DaysSampleKeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DistributionDate {
            get {
                return ResourceManager.GetString("DistributionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Equivalent {
            get {
                return ResourceManager.GetString("Equivalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 到期日.
        /// </summary>
        internal static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FlashPoint {
            get {
                return ResourceManager.GetString("FlashPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用数据.
        /// </summary>
        internal static string GeneralData {
            get {
                return ResourceManager.GetString("GeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年级.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人力资源.
        /// </summary>
        internal static string HumanResources {
            get {
                return ResourceManager.GetString("HumanResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 器具发放.
        /// </summary>
        internal static string InstrumentRelease {
            get {
                return ResourceManager.GetString("InstrumentRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 器具归还.
        /// </summary>
        internal static string InstrumentReturn {
            get {
                return ResourceManager.GetString("InstrumentReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 器具入库.
        /// </summary>
        internal static string InstrumentStorage {
            get {
                return ResourceManager.GetString("InstrumentStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是实验室LT.
        /// </summary>
        internal static string IsLabLT {
            get {
                return ResourceManager.GetString("IsLabLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsResale.
        /// </summary>
        internal static string IsResale {
            get {
                return ResourceManager.GetString("IsResale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有毒.
        /// </summary>
        internal static string IsToxic {
            get {
                return ResourceManager.GetString("IsToxic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是供应商LT.
        /// </summary>
        internal static string IsVendorLT {
            get {
                return ResourceManager.GetString("IsVendorLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目名.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品描述.
        /// </summary>
        internal static string Item_Description {
            get {
                return ResourceManager.GetString("Item Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目/单位.
        /// </summary>
        internal static string Item_Unit {
            get {
                return ResourceManager.GetString("Item/Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制造商.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MatrixName {
            get {
                return ResourceManager.GetString("MatrixName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计量业务.
        /// </summary>
        internal static string MeasurementBusiness {
            get {
                return ResourceManager.GetString("MeasurementBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MeltingPoint {
            get {
                return ResourceManager.GetString("MeltingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MethodNumber {
            get {
                return ResourceManager.GetString("MethodNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制造商猫号.
        /// </summary>
        internal static string MfrcatNum {
            get {
                return ResourceManager.GetString("MfrcatNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制造项目名称.
        /// </summary>
        internal static string MfritemName {
            get {
                return ResourceManager.GetString("MfritemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的账号.
        /// </summary>
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包装单位.
        /// </summary>
        internal static string PackUnits {
            get {
                return ResourceManager.GetString("PackUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ParameterName {
            get {
                return ResourceManager.GetString("ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCTypeName.
        /// </summary>
        internal static string QCTypeName {
            get {
                return ResourceManager.GetString("QCTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质检业务.
        /// </summary>
        internal static string QualityTestingBusiness {
            get {
                return ResourceManager.GetString("QualityTestingBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemainderDaysInAdvance.
        /// </summary>
        internal static string RemainderDaysInAdvance {
            get {
                return ResourceManager.GetString("RemainderDaysInAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报告批准.
        /// </summary>
        internal static string ReportApproval {
            get {
                return ResourceManager.GetString("ReportApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报告打印.
        /// </summary>
        internal static string ReportPrint {
            get {
                return ResourceManager.GetString("ReportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报告审核.
        /// </summary>
        internal static string ReportReview {
            get {
                return ResourceManager.GetString("ReportReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报表.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果登记.
        /// </summary>
        internal static string ResultEntry {
            get {
                return ResourceManager.GetString("ResultEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退休日期.
        /// </summary>
        internal static string RetireDate {
            get {
                return ResourceManager.GetString("RetireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 归还确认.
        /// </summary>
        internal static string ReturnConfirmation {
            get {
                return ResourceManager.GetString("ReturnConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索导航项.
        /// </summary>
        internal static string Search_Navigation_item {
            get {
                return ResourceManager.GetString("Search Navigation item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 规格.
        /// </summary>
        internal static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StandardClause.
        /// </summary>
        internal static string StandardClause {
            get {
                return ResourceManager.GetString("StandardClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 库存数量.
        /// </summary>
        internal static string StockQty {
            get {
                return ResourceManager.GetString("StockQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存储.
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Synonym {
            get {
                return ResourceManager.GetString("Synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统管理.
        /// </summary>
        internal static string SystemManagement {
            get {
                return ResourceManager.GetString("SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务分配.
        /// </summary>
        internal static string TaskAssignment {
            get {
                return ResourceManager.GetString("TaskAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务领取.
        /// </summary>
        internal static string TaskReceipt {
            get {
                return ResourceManager.GetString("TaskReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TestCode {
            get {
                return ResourceManager.GetString("TestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单价.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商.
        /// </summary>
        internal static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商商品名称.
        /// </summary>
        internal static string VendorItemName {
            get {
                return ResourceManager.GetString("VendorItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Vendorlt {
            get {
                return ResourceManager.GetString("Vendorlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VisualMatrixName {
            get {
                return ResourceManager.GetString("VisualMatrixName", resourceCulture);
            }
        }
    }
}
