//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizeSuboutResultEntryChinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeSuboutResultEntryChinese() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizeSuboutResultEntryChinese", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分析人.
        /// </summary>
        internal static string AnalyzedBy {
            get {
                return ResourceManager.GetString("AnalyzedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalyzedDate.
        /// </summary>
        internal static string AnalyzedDate {
            get {
                return ResourceManager.GetString("AnalyzedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批准人.
        /// </summary>
        internal static string ApprovedBy {
            get {
                return ResourceManager.GetString("ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApprovedDate.
        /// </summary>
        internal static string ApprovedDate {
            get {
                return ResourceManager.GetString("ApprovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 委托样品名称.
        /// </summary>
        internal static string ClientSampleID {
            get {
                return ResourceManager.GetString("ClientSampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期分析.
        /// </summary>
        internal static string DateAnalyzed {
            get {
                return ResourceManager.GetString("DateAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批准日期.
        /// </summary>
        internal static string DateApproved {
            get {
                return ResourceManager.GetString("DateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期验证.
        /// </summary>
        internal static string DateValidated {
            get {
                return ResourceManager.GetString("DateValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稀释倍数.
        /// </summary>
        internal static string DF {
            get {
                return ResourceManager.GetString("DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作编号.
        /// </summary>
        internal static string JobID {
            get {
                return ResourceManager.GetString("JobID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低标定浓度.
        /// </summary>
        internal static string LOQ {
            get {
                return ResourceManager.GetString("LOQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矩阵.
        /// </summary>
        internal static string Matrix {
            get {
                return ResourceManager.GetString("Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检出限.
        /// </summary>
        internal static string MDL {
            get {
                return ResourceManager.GetString("MDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法名.
        /// </summary>
        internal static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数值结果.
        /// </summary>
        internal static string NumericResult {
            get {
                return ResourceManager.GetString("NumericResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型.
        /// </summary>
        internal static string QcType {
            get {
                return ResourceManager.GetString("QcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接收限制.
        /// </summary>
        internal static string RecLCLimit {
            get {
                return ResourceManager.GetString("RecLCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接收限制.
        /// </summary>
        internal static string RecUCLimit {
            get {
                return ResourceManager.GetString("RecUCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPDCH限制.
        /// </summary>
        internal static string RPDLCLimit {
            get {
                return ResourceManager.GetString("RPDLCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPDCL限制.
        /// </summary>
        internal static string RPDUCLimit {
            get {
                return ResourceManager.GetString("RPDUCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报告限.
        /// </summary>
        internal static string RptLimit {
            get {
                return ResourceManager.GetString("RptLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样品编号.
        /// </summary>
        internal static string SampleID {
            get {
                return ResourceManager.GetString("SampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleName.
        /// </summary>
        internal static string SampleName {
            get {
                return ResourceManager.GetString("SampleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加标量.
        /// </summary>
        internal static string SpikeAmount {
            get {
                return ResourceManager.GetString("SpikeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分包订单号.
        /// </summary>
        internal static string SuboutOrderID {
            get {
                return ResourceManager.GetString("SuboutOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单位.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高标定浓度.
        /// </summary>
        internal static string UQL {
            get {
                return ResourceManager.GetString("UQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审核人.
        /// </summary>
        internal static string ValidatedBy {
            get {
                return ResourceManager.GetString("ValidatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidatedDate.
        /// </summary>
        internal static string ValidatedDate {
            get {
                return ResourceManager.GetString("ValidatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %恢复.
        /// </summary>
        internal static string _Recovery {
            get {
                return ResourceManager.GetString("%Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相对偏差.
        /// </summary>
        internal static string _RPD {
            get {
                return ResourceManager.GetString("%RPD", resourceCulture);
            }
        }
    }
}
