//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizeSuboutResultEntryEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeSuboutResultEntryEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizeSuboutResultEntryEnglish", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalyzedBy.
        /// </summary>
        internal static string AnalyzedBy {
            get {
                return ResourceManager.GetString("AnalyzedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalyzedDate.
        /// </summary>
        internal static string AnalyzedDate {
            get {
                return ResourceManager.GetString("AnalyzedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApprovedBy.
        /// </summary>
        internal static string ApprovedBy {
            get {
                return ResourceManager.GetString("ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApprovedDate.
        /// </summary>
        internal static string ApprovedDate {
            get {
                return ResourceManager.GetString("ApprovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientSampleID.
        /// </summary>
        internal static string ClientSampleID {
            get {
                return ResourceManager.GetString("ClientSampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateAnalyzed.
        /// </summary>
        internal static string DateAnalyzed {
            get {
                return ResourceManager.GetString("DateAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateApproved.
        /// </summary>
        internal static string DateApproved {
            get {
                return ResourceManager.GetString("DateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateValidated.
        /// </summary>
        internal static string DateValidated {
            get {
                return ResourceManager.GetString("DateValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DF.
        /// </summary>
        internal static string DF {
            get {
                return ResourceManager.GetString("DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobID.
        /// </summary>
        internal static string JobID {
            get {
                return ResourceManager.GetString("JobID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOQ.
        /// </summary>
        internal static string LOQ {
            get {
                return ResourceManager.GetString("LOQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        internal static string Matrix {
            get {
                return ResourceManager.GetString("Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDL.
        /// </summary>
        internal static string MDL {
            get {
                return ResourceManager.GetString("MDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodName.
        /// </summary>
        internal static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumericResult.
        /// </summary>
        internal static string NumericResult {
            get {
                return ResourceManager.GetString("NumericResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QcType.
        /// </summary>
        internal static string QcType {
            get {
                return ResourceManager.GetString("QcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecLCLimit.
        /// </summary>
        internal static string RecLCLimit {
            get {
                return ResourceManager.GetString("RecLCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecUCLimit.
        /// </summary>
        internal static string RecUCLimit {
            get {
                return ResourceManager.GetString("RecUCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPDLCLimit.
        /// </summary>
        internal static string RPDLCLimit {
            get {
                return ResourceManager.GetString("RPDLCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPDUCLimit.
        /// </summary>
        internal static string RPDUCLimit {
            get {
                return ResourceManager.GetString("RPDUCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RptLimit.
        /// </summary>
        internal static string RptLimit {
            get {
                return ResourceManager.GetString("RptLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleID.
        /// </summary>
        internal static string SampleID {
            get {
                return ResourceManager.GetString("SampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleName.
        /// </summary>
        internal static string SampleName {
            get {
                return ResourceManager.GetString("SampleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpikeAmount.
        /// </summary>
        internal static string SpikeAmount {
            get {
                return ResourceManager.GetString("SpikeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuboutOrderID.
        /// </summary>
        internal static string SuboutOrderID {
            get {
                return ResourceManager.GetString("SuboutOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UQL.
        /// </summary>
        internal static string UQL {
            get {
                return ResourceManager.GetString("UQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidatedBy.
        /// </summary>
        internal static string ValidatedBy {
            get {
                return ResourceManager.GetString("ValidatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidatedDate.
        /// </summary>
        internal static string ValidatedDate {
            get {
                return ResourceManager.GetString("ValidatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %Recovery.
        /// </summary>
        internal static string _Recovery {
            get {
                return ResourceManager.GetString("%Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %RPD.
        /// </summary>
        internal static string _RPD {
            get {
                return ResourceManager.GetString("%RPD", resourceCulture);
            }
        }
    }
}
