//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizeResourcesEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeResourcesEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizeResourcesEnglish", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertQty.
        /// </summary>
        internal static string AlertQty {
            get {
                return ResourceManager.GetString("AlertQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmountUnit.
        /// </summary>
        internal static string AmountUnit {
            get {
                return ResourceManager.GetString("AmountUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Center.
        /// </summary>
        internal static string ApplicationCenter {
            get {
                return ResourceManager.GetString("ApplicationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Management.
        /// </summary>
        internal static string AssetManagement {
            get {
                return ResourceManager.GetString("AssetManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Archiving.
        /// </summary>
        internal static string BusinessArchiving {
            get {
                return ResourceManager.GetString("BusinessArchiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business System.
        /// </summary>
        internal static string BusinessSystem {
            get {
                return ResourceManager.GetString("BusinessSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog#.
        /// </summary>
        internal static string Catalog_ {
            get {
                return ResourceManager.GetString("Catalog#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Reception.
        /// </summary>
        internal static string CertificateReception {
            get {
                return ResourceManager.GetString("CertificateReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Release.
        /// </summary>
        internal static string CertificateRelease {
            get {
                return ResourceManager.GetString("CertificateRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Management.
        /// </summary>
        internal static string CustomerManagement {
            get {
                return ResourceManager.GetString("CustomerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistributionDate.
        /// </summary>
        internal static string DistributionDate {
            get {
                return ResourceManager.GetString("DistributionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiryDate.
        /// </summary>
        internal static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Data.
        /// </summary>
        internal static string GeneralData {
            get {
                return ResourceManager.GetString("GeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources.
        /// </summary>
        internal static string HumanResources {
            get {
                return ResourceManager.GetString("HumanResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Release.
        /// </summary>
        internal static string InstrumentRelease {
            get {
                return ResourceManager.GetString("InstrumentRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Return.
        /// </summary>
        internal static string InstrumentReturn {
            get {
                return ResourceManager.GetString("InstrumentReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Storage.
        /// </summary>
        internal static string InstrumentStorage {
            get {
                return ResourceManager.GetString("InstrumentStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLabLT.
        /// </summary>
        internal static string IsLabLT {
            get {
                return ResourceManager.GetString("IsLabLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsResale.
        /// </summary>
        internal static string IsResale {
            get {
                return ResourceManager.GetString("IsResale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsToxic.
        /// </summary>
        internal static string IsToxic {
            get {
                return ResourceManager.GetString("IsToxic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsVendorLT.
        /// </summary>
        internal static string IsVendorLT {
            get {
                return ResourceManager.GetString("IsVendorLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemName.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        internal static string Item_Description {
            get {
                return ResourceManager.GetString("Item Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item/Unit.
        /// </summary>
        internal static string Item_Unit {
            get {
                return ResourceManager.GetString("Item/Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Business.
        /// </summary>
        internal static string MeasurementBusiness {
            get {
                return ResourceManager.GetString("MeasurementBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MfrcatNum.
        /// </summary>
        internal static string MfrcatNum {
            get {
                return ResourceManager.GetString("MfrcatNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MfritemName.
        /// </summary>
        internal static string MfritemName {
            get {
                return ResourceManager.GetString("MfritemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackUnits.
        /// </summary>
        internal static string PackUnits {
            get {
                return ResourceManager.GetString("PackUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Testing Business.
        /// </summary>
        internal static string QualityTestingBusiness {
            get {
                return ResourceManager.GetString("QualityTestingBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemainderDaysInAdvance.
        /// </summary>
        internal static string RemainderDaysInAdvance {
            get {
                return ResourceManager.GetString("RemainderDaysInAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Approval.
        /// </summary>
        internal static string ReportApproval {
            get {
                return ResourceManager.GetString("ReportApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Print.
        /// </summary>
        internal static string ReportPrint {
            get {
                return ResourceManager.GetString("ReportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Review.
        /// </summary>
        internal static string ReportReview {
            get {
                return ResourceManager.GetString("ReportReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Entry.
        /// </summary>
        internal static string ResultEntry {
            get {
                return ResourceManager.GetString("ResultEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetireDate.
        /// </summary>
        internal static string RetireDate {
            get {
                return ResourceManager.GetString("RetireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Confirmation.
        /// </summary>
        internal static string ReturnConfirmation {
            get {
                return ResourceManager.GetString("ReturnConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Navigation Item.
        /// </summary>
        internal static string Search_Navigation_Item {
            get {
                return ResourceManager.GetString("Search Navigation Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification.
        /// </summary>
        internal static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockQty.
        /// </summary>
        internal static string StockQty {
            get {
                return ResourceManager.GetString("StockQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Management.
        /// </summary>
        internal static string SystemManagement {
            get {
                return ResourceManager.GetString("SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Assignment.
        /// </summary>
        internal static string TaskAssignment {
            get {
                return ResourceManager.GetString("TaskAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Receipt.
        /// </summary>
        internal static string TaskReceipt {
            get {
                return ResourceManager.GetString("TaskReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Item Name.
        /// </summary>
        internal static string VendorItemName {
            get {
                return ResourceManager.GetString("VendorItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VendorLT.
        /// </summary>
        internal static string Vendorlt {
            get {
                return ResourceManager.GetString("Vendorlt", resourceCulture);
            }
        }
    }
}
