//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizeResultEntryEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeResultEntryEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizeResultEntryEnglish", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalyzedBy.
        /// </summary>
        internal static string AnalyzedBy {
            get {
                return ResourceManager.GetString("AnalyzedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientSampleID.
        /// </summary>
        internal static string ClientSampleID {
            get {
                return ResourceManager.GetString("ClientSampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateAnalyzed.
        /// </summary>
        internal static string DateAnalyzed {
            get {
                return ResourceManager.GetString("DateAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DF.
        /// </summary>
        internal static string DF {
            get {
                return ResourceManager.GetString("DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        internal static string Matrix {
            get {
                return ResourceManager.GetString("Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDL.
        /// </summary>
        internal static string MDL {
            get {
                return ResourceManager.GetString("MDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumericResult.
        /// </summary>
        internal static string NumericResult {
            get {
                return ResourceManager.GetString("NumericResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCBatchID.
        /// </summary>
        internal static string QCBatchID {
            get {
                return ResourceManager.GetString("QCBatchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QcType.
        /// </summary>
        internal static string QcType {
            get {
                return ResourceManager.GetString("QcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec.
        /// </summary>
        internal static string Rec {
            get {
                return ResourceManager.GetString("Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPD.
        /// </summary>
        internal static string RPD {
            get {
                return ResourceManager.GetString("RPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RptLimit.
        /// </summary>
        internal static string RptLimit {
            get {
                return ResourceManager.GetString("RptLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpikeAmount.
        /// </summary>
        internal static string SpikeAmount {
            get {
                return ResourceManager.GetString("SpikeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpikeAmountUnit.
        /// </summary>
        internal static string SpikeAmountUnit {
            get {
                return ResourceManager.GetString("SpikeAmountUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SysSampleCode.
        /// </summary>
        internal static string SysSampleCode {
            get {
                return ResourceManager.GetString("SysSampleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
    }
}
