//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SDMS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SDMS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SDMS", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        internal static string Accounting_En {
            get {
                return ResourceManager.GetString("Accounting_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountingC.
        /// </summary>
        internal static string Accounting_zh_CN {
            get {
                return ResourceManager.GetString("Accounting_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentBottom.
        /// </summary>
        internal static string AlignmentBottom_En {
            get {
                return ResourceManager.GetString("AlignmentBottom_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentBottomC.
        /// </summary>
        internal static string AlignmentBottom_zh_CN {
            get {
                return ResourceManager.GetString("AlignmentBottom_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentCenter.
        /// </summary>
        internal static string AlignmentCenter_En {
            get {
                return ResourceManager.GetString("AlignmentCenter_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentCenterC.
        /// </summary>
        internal static string AlignmentCenter_zh_CN {
            get {
                return ResourceManager.GetString("AlignmentCenter_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentLeft.
        /// </summary>
        internal static string AlignmentLeft_En {
            get {
                return ResourceManager.GetString("AlignmentLeft_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentLeftC.
        /// </summary>
        internal static string AlignmentLeft_zh_CN {
            get {
                return ResourceManager.GetString("AlignmentLeft_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentMiddle.
        /// </summary>
        internal static string AlignmentMiddle_En {
            get {
                return ResourceManager.GetString("AlignmentMiddle_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentMiddleC.
        /// </summary>
        internal static string AlignmentMiddle_zh_CN {
            get {
                return ResourceManager.GetString("AlignmentMiddle_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentRight.
        /// </summary>
        internal static string AlignmentRight_En {
            get {
                return ResourceManager.GetString("AlignmentRight_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentRightC.
        /// </summary>
        internal static string AlignmentRight_zh_CN {
            get {
                return ResourceManager.GetString("AlignmentRight_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentTop.
        /// </summary>
        internal static string AlignmentTop_En {
            get {
                return ResourceManager.GetString("AlignmentTop_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentTopC.
        /// </summary>
        internal static string AlignmentTop_zh_CN {
            get {
                return ResourceManager.GetString("AlignmentTop_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string Alignment_En {
            get {
                return ResourceManager.GetString("Alignment_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对齐方式.
        /// </summary>
        internal static string Alignment_zh_CN {
            get {
                return ResourceManager.GetString("Alignment_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABID.
        /// </summary>
        internal static string AnalyticalBatch_En {
            get {
                return ResourceManager.GetString("AnalyticalBatch_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分析批次.
        /// </summary>
        internal static string AnalyticalBatch_zh_CN {
            get {
                return ResourceManager.GetString("AnalyticalBatch_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area_En {
            get {
                return ResourceManager.GetString("Area_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区域图.
        /// </summary>
        internal static string Area_zh_CN {
            get {
                return ResourceManager.GetString("Area_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSum.
        /// </summary>
        internal static string AutoSum_En {
            get {
                return ResourceManager.GetString("AutoSum_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动求和.
        /// </summary>
        internal static string AutoSum_zh_CN {
            get {
                return ResourceManager.GetString("AutoSum_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string Bar_En {
            get {
                return ResourceManager.GetString("Bar_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条形图.
        /// </summary>
        internal static string Bar_zh_CN {
            get {
                return ResourceManager.GetString("Bar_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindGrid.
        /// </summary>
        internal static string BindGrid_En {
            get {
                return ResourceManager.GetString("BindGrid_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定表格.
        /// </summary>
        internal static string BindGrid_zh_CN {
            get {
                return ResourceManager.GetString("BindGrid_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BorderLineColor.
        /// </summary>
        internal static string BorderLineColor_En {
            get {
                return ResourceManager.GetString("BorderLineColor_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BorderLineColorC.
        /// </summary>
        internal static string BorderLineColor_zh_CN {
            get {
                return ResourceManager.GetString("BorderLineColor_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borders.
        /// </summary>
        internal static string Borders_En {
            get {
                return ResourceManager.GetString("Borders_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BordersC.
        /// </summary>
        internal static string Borders_zh_CN {
            get {
                return ResourceManager.GetString("Borders_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculationNow.
        /// </summary>
        internal static string Calculate_Now_En {
            get {
                return ResourceManager.GetString("Calculate Now_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始计算.
        /// </summary>
        internal static string Calculate_Now_zh_CN {
            get {
                return ResourceManager.GetString("Calculate Now_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculationSheet.
        /// </summary>
        internal static string Calculate_Sheet_En {
            get {
                return ResourceManager.GetString("Calculate Sheet_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算工作表.
        /// </summary>
        internal static string Calculate_Sheet_zh_CN {
            get {
                return ResourceManager.GetString("Calculate Sheet_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        internal static string Calculation_En {
            get {
                return ResourceManager.GetString("Calculation_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Options.
        /// </summary>
        internal static string Calculation_Options_En {
            get {
                return ResourceManager.GetString("Calculation Options_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算选项.
        /// </summary>
        internal static string Calculation_Options_zh_CN {
            get {
                return ResourceManager.GetString("Calculation Options_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算.
        /// </summary>
        internal static string Calculation_zh_CN {
            get {
                return ResourceManager.GetString("Calculation_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalibratedBy.
        /// </summary>
        internal static string CalibratedBy_En {
            get {
                return ResourceManager.GetString("CalibratedBy_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校準者.
        /// </summary>
        internal static string CalibratedBy_zh_CN {
            get {
                return ResourceManager.GetString("CalibratedBy_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalibratedDate.
        /// </summary>
        internal static string CalibratedDate_En {
            get {
                return ResourceManager.GetString("CalibratedDate_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校準日期.
        /// </summary>
        internal static string CalibratedDate_zh_CN {
            get {
                return ResourceManager.GetString("CalibratedDate_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalibrationID.
        /// </summary>
        internal static string CalibrationID_En {
            get {
                return ResourceManager.GetString("CalibrationID_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校准ID.
        /// </summary>
        internal static string CalibrationID_zh_CN {
            get {
                return ResourceManager.GetString("CalibrationID_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel_En {
            get {
                return ResourceManager.GetString("Cancel_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Cancel_zh_CN {
            get {
                return ResourceManager.GetString("Cancel_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells.
        /// </summary>
        internal static string Cells_En {
            get {
                return ResourceManager.GetString("Cells_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元格.
        /// </summary>
        internal static string Cells_zh_CN {
            get {
                return ResourceManager.GetString("Cells_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChartOthers.
        /// </summary>
        internal static string ChartOthers_En {
            get {
                return ResourceManager.GetString("ChartOthers_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他图表.
        /// </summary>
        internal static string ChartOthers_zh_CN {
            get {
                return ResourceManager.GetString("ChartOthers_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        internal static string Charts_En {
            get {
                return ResourceManager.GetString("Charts_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图表.
        /// </summary>
        internal static string Charts_zh_CN {
            get {
                return ResourceManager.GetString("Charts_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear_En {
            get {
                return ResourceManager.GetString("Clear_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        internal static string Clear_zh_CN {
            get {
                return ResourceManager.GetString("Clear_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string Client_En {
            get {
                return ResourceManager.GetString("Client_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Client_zh_CN {
            get {
                return ResourceManager.GetString("Client_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string Clipboard_EN {
            get {
                return ResourceManager.GetString("Clipboard_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪贴板.
        /// </summary>
        internal static string Clipboard_zh_CN {
            get {
                return ResourceManager.GetString("Clipboard_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close_En {
            get {
                return ResourceManager.GetString("Close_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string Close_zh_CN {
            get {
                return ResourceManager.GetString("Close_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Column_En {
            get {
                return ResourceManager.GetString("Column_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柱状图.
        /// </summary>
        internal static string Column_zh_CN {
            get {
                return ResourceManager.GetString("Column_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommaStyle.
        /// </summary>
        internal static string CommaStyle_En {
            get {
                return ResourceManager.GetString("CommaStyle_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommaStyleC.
        /// </summary>
        internal static string CommaStyle_zh_CN {
            get {
                return ResourceManager.GetString("CommaStyle_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Common_En {
            get {
                return ResourceManager.GetString("Common_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规.
        /// </summary>
        internal static string Common_zh_CN {
            get {
                return ResourceManager.GetString("Common_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete_En {
            get {
                return ResourceManager.GetString("Complete_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        internal static string Complete_zh_CN {
            get {
                return ResourceManager.GetString("Complete_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy_En {
            get {
                return ResourceManager.GetString("Copy_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        internal static string Copy_zh_CN {
            get {
                return ResourceManager.GetString("Copy_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut_En {
            get {
                return ResourceManager.GetString("Cut_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        internal static string Cut_zh_CN {
            get {
                return ResourceManager.GetString("Cut_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data_En {
            get {
                return ResourceManager.GetString("Data_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Tools.
        /// </summary>
        internal static string Data_Tools_En {
            get {
                return ResourceManager.GetString("Data Tools_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据工具.
        /// </summary>
        internal static string Data_Tools_zh_CN {
            get {
                return ResourceManager.GetString("Data Tools_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Validation.
        /// </summary>
        internal static string Data_Validation_En {
            get {
                return ResourceManager.GetString("Data Validation_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据验证.
        /// </summary>
        internal static string Data_Validation_zh_CN {
            get {
                return ResourceManager.GetString("Data Validation_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据.
        /// </summary>
        internal static string Data_zh_CN {
            get {
                return ResourceManager.GetString("Data_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateAndTime.
        /// </summary>
        internal static string DateAndTime_En {
            get {
                return ResourceManager.GetString("DateAndTime_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期和时间.
        /// </summary>
        internal static string DateAndTime_zh_CN {
            get {
                return ResourceManager.GetString("DateAndTime_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateReceived.
        /// </summary>
        internal static string DateReceived_En {
            get {
                return ResourceManager.GetString("DateReceived_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecreaseDecimal.
        /// </summary>
        internal static string DecreaseDecimal_En {
            get {
                return ResourceManager.GetString("DecreaseDecimal_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecreaseDecimalC.
        /// </summary>
        internal static string DecreaseDecimal_zh_CN {
            get {
                return ResourceManager.GetString("DecreaseDecimal_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecreaseFontSize.
        /// </summary>
        internal static string DecreaseFontSize_En {
            get {
                return ResourceManager.GetString("DecreaseFontSize_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecreaseFontSizeC.
        /// </summary>
        internal static string DecreaseFontSize_zh_CN {
            get {
                return ResourceManager.GetString("DecreaseFontSize_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecreaseIndent.
        /// </summary>
        internal static string DecreaseIndent_En {
            get {
                return ResourceManager.GetString("DecreaseIndent_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecreaseIndentC.
        /// </summary>
        internal static string DecreaseIndent_zh_Cn {
            get {
                return ResourceManager.GetString("DecreaseIndent_zh-Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete_En {
            get {
                return ResourceManager.GetString("Delete_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string Delete_zh_CN {
            get {
                return ResourceManager.GetString("Delete_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentViews.
        /// </summary>
        internal static string DocumentViews_En {
            get {
                return ResourceManager.GetString("DocumentViews_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文档视图.
        /// </summary>
        internal static string DocumentViews_zh_CN {
            get {
                return ResourceManager.GetString("DocumentViews_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DueDate.
        /// </summary>
        internal static string DueDate_En {
            get {
                return ResourceManager.GetString("DueDate_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditComment.
        /// </summary>
        internal static string EditComment_En {
            get {
                return ResourceManager.GetString("EditComment_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑批注.
        /// </summary>
        internal static string EditComment_zh_CN {
            get {
                return ResourceManager.GetString("EditComment_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditingFindAndSelect.
        /// </summary>
        internal static string EditingFindAndSelect_En {
            get {
                return ResourceManager.GetString("EditingFindAndSelect_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditingFindAndSelectC.
        /// </summary>
        internal static string EditingFindAndSelect_zh_CN {
            get {
                return ResourceManager.GetString("EditingFindAndSelect_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string Editing_En {
            get {
                return ResourceManager.GetString("Editing_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        internal static string Editing_zh_CN {
            get {
                return ResourceManager.GetString("Editing_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit_En {
            get {
                return ResourceManager.GetString("Edit_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        internal static string Edit_zh_CN {
            get {
                return ResourceManager.GetString("Edit_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Enter_En {
            get {
                return ResourceManager.GetString("Enter_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 键入.
        /// </summary>
        internal static string Enter_zh_CN {
            get {
                return ResourceManager.GetString("Enter_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel Files.
        /// </summary>
        internal static string ExportExlFiles_En {
            get {
                return ResourceManager.GetString("ExportExlFiles_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Excel Files.
        /// </summary>
        internal static string ExportExlFiles_zh_CN {
            get {
                return ResourceManager.GetString("ExportExlFiles_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Files.
        /// </summary>
        internal static string ExportFiles_En {
            get {
                return ResourceManager.GetString("ExportFiles_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Files.
        /// </summary>
        internal static string ExportFiles_zh_CN {
            get {
                return ResourceManager.GetString("ExportFiles_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePrint.
        /// </summary>
        internal static string FilePrint_En {
            get {
                return ResourceManager.GetString("FilePrint_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePrintC.
        /// </summary>
        internal static string FilePrint_zh_CN {
            get {
                return ResourceManager.GetString("FilePrint_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File_En {
            get {
                return ResourceManager.GetString("File_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        internal static string File_zh_CN {
            get {
                return ResourceManager.GetString("File_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillColor.
        /// </summary>
        internal static string FillColor_En {
            get {
                return ResourceManager.GetString("FillColor_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillColorC.
        /// </summary>
        internal static string FillColor_zh_CN {
            get {
                return ResourceManager.GetString("FillColor_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string Fill_En {
            get {
                return ResourceManager.GetString("Fill_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 填充.
        /// </summary>
        internal static string Fill_zh_CN {
            get {
                return ResourceManager.GetString("Fill_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter_En {
            get {
                return ResourceManager.GetString("Filter_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 筛选.
        /// </summary>
        internal static string Filter_zh_CN {
            get {
                return ResourceManager.GetString("Filter_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial.
        /// </summary>
        internal static string Financial_En {
            get {
                return ResourceManager.GetString("Financial_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 财务.
        /// </summary>
        internal static string Financial_zh_CN {
            get {
                return ResourceManager.GetString("Financial_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find_En {
            get {
                return ResourceManager.GetString("Find_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找.
        /// </summary>
        internal static string Find_zh_CN {
            get {
                return ResourceManager.GetString("Find_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontBold.
        /// </summary>
        internal static string FontBold_En {
            get {
                return ResourceManager.GetString("FontBold_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontBoldC.
        /// </summary>
        internal static string FontBold_zh_CN {
            get {
                return ResourceManager.GetString("FontBold_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontColor.
        /// </summary>
        internal static string FontColor_En {
            get {
                return ResourceManager.GetString("FontColor_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontColorC.
        /// </summary>
        internal static string FontColor_zh_CN {
            get {
                return ResourceManager.GetString("FontColor_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontItalic.
        /// </summary>
        internal static string FontItalic_En {
            get {
                return ResourceManager.GetString("FontItalic_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontItalicC.
        /// </summary>
        internal static string FontItalic_zh_CN {
            get {
                return ResourceManager.GetString("FontItalic_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontName.
        /// </summary>
        internal static string FontName_En {
            get {
                return ResourceManager.GetString("FontName_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontNameC.
        /// </summary>
        internal static string FontName_zh_CN {
            get {
                return ResourceManager.GetString("FontName_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontSize.
        /// </summary>
        internal static string FontSize_En {
            get {
                return ResourceManager.GetString("FontSize_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontSizeC.
        /// </summary>
        internal static string FontSize_zh_CN {
            get {
                return ResourceManager.GetString("FontSize_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontStrikeOut.
        /// </summary>
        internal static string FontStrikeOut_En {
            get {
                return ResourceManager.GetString("FontStrikeOut_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontStrikeOutC.
        /// </summary>
        internal static string FontStrikeOut_zh_CN {
            get {
                return ResourceManager.GetString("FontStrikeOut_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontUnderline.
        /// </summary>
        internal static string FontUnderline_En {
            get {
                return ResourceManager.GetString("FontUnderline_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontUnderlineC.
        /// </summary>
        internal static string FontUnderline_zh_CN {
            get {
                return ResourceManager.GetString("FontUnderline_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font_En {
            get {
                return ResourceManager.GetString("Font_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体.
        /// </summary>
        internal static string Font_zh_CN {
            get {
                return ResourceManager.GetString("Font_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format as Table.
        /// </summary>
        internal static string Format_as_Table_En {
            get {
                return ResourceManager.GetString("Format as Table_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式化表格.
        /// </summary>
        internal static string Format_as_Table_zh_CN {
            get {
                return ResourceManager.GetString("Format as Table_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format_En {
            get {
                return ResourceManager.GetString("Format_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式.
        /// </summary>
        internal static string Format_zh_CN {
            get {
                return ResourceManager.GetString("Format_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulas.
        /// </summary>
        internal static string Formulas_En {
            get {
                return ResourceManager.GetString("Formulas_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公式.
        /// </summary>
        internal static string Formulas_zh_CN {
            get {
                return ResourceManager.GetString("Formulas_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Panes.
        /// </summary>
        internal static string FreezePanes_En {
            get {
                return ResourceManager.GetString("FreezePanes_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冻结窗格.
        /// </summary>
        internal static string FreezePanes_zh_CN {
            get {
                return ResourceManager.GetString("FreezePanes_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string FullScreen_En {
            get {
                return ResourceManager.GetString("FullScreen_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全屏.
        /// </summary>
        internal static string FullScreen_zh_CN {
            get {
                return ResourceManager.GetString("FullScreen_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionLibrary.
        /// </summary>
        internal static string FunctionLibrary_En {
            get {
                return ResourceManager.GetString("FunctionLibrary_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 函数库.
        /// </summary>
        internal static string FunctionLibrary_zh_CN {
            get {
                return ResourceManager.GetString("FunctionLibrary_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string GenerateReports_En {
            get {
                return ResourceManager.GetString("GenerateReports_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报告.
        /// </summary>
        internal static string GenerateReports_zh_CN {
            get {
                return ResourceManager.GetString("GenerateReports_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gridlines.
        /// </summary>
        internal static string Gridlines_En {
            get {
                return ResourceManager.GetString("Gridlines_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网格线.
        /// </summary>
        internal static string Gridlines_zh_CN {
            get {
                return ResourceManager.GetString("Gridlines_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headings.
        /// </summary>
        internal static string Headings_En {
            get {
                return ResourceManager.GetString("Headings_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        internal static string Headings_zh_CN {
            get {
                return ResourceManager.GetString("Headings_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_En {
            get {
                return ResourceManager.GetString("Home_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始.
        /// </summary>
        internal static string Home_zh_CN {
            get {
                return ResourceManager.GetString("Home_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        internal static string Hyperlink_En {
            get {
                return ResourceManager.GetString("Hyperlink_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超链接.
        /// </summary>
        internal static string Hyperlink_zh_CN {
            get {
                return ResourceManager.GetString("Hyperlink_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrations.
        /// </summary>
        internal static string Illustrations_En {
            get {
                return ResourceManager.GetString("Illustrations_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插图.
        /// </summary>
        internal static string Illustrations_zh_CN {
            get {
                return ResourceManager.GetString("Illustrations_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Excel Files.
        /// </summary>
        internal static string ImportExlFiles_En {
            get {
                return ResourceManager.GetString("ImportExlFiles_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Excel Files.
        /// </summary>
        internal static string ImportExlFiles_zh_CN {
            get {
                return ResourceManager.GetString("ImportExlFiles_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Files.
        /// </summary>
        internal static string ImportFiles_En {
            get {
                return ResourceManager.GetString("ImportFiles_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入文件.
        /// </summary>
        internal static string ImportFiles_zh_CN {
            get {
                return ResourceManager.GetString("ImportFiles_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Instrument File.
        /// </summary>
        internal static string ImportInstrumentFile_En {
            get {
                return ResourceManager.GetString("ImportInstrumentFile_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪器结果导入.
        /// </summary>
        internal static string ImportInstrumentFile_zh_CN {
            get {
                return ResourceManager.GetString("ImportInstrumentFile_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncreaseDecimal.
        /// </summary>
        internal static string IncreaseDecimal_En {
            get {
                return ResourceManager.GetString("IncreaseDecimal_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncreaseDecimalC.
        /// </summary>
        internal static string IncreaseDecimal_zh_CN {
            get {
                return ResourceManager.GetString("IncreaseDecimal_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncreaseFontSize.
        /// </summary>
        internal static string IncreaseFontSize_En {
            get {
                return ResourceManager.GetString("IncreaseFontSize_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncreaseFontSizeC.
        /// </summary>
        internal static string IncreaseFontSize_zh_CN {
            get {
                return ResourceManager.GetString("IncreaseFontSize_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncreaseIndent.
        /// </summary>
        internal static string IncreaseIndent_En {
            get {
                return ResourceManager.GetString("IncreaseIndent_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncreaseIndentC.
        /// </summary>
        internal static string IncreaseIndent_zh_CN {
            get {
                return ResourceManager.GetString("IncreaseIndent_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert_En {
            get {
                return ResourceManager.GetString("Insert_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入.
        /// </summary>
        internal static string Insert_zh_CN {
            get {
                return ResourceManager.GetString("Insert_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISABIDLink.
        /// </summary>
        internal static string ISABIDLink_En {
            get {
                return ResourceManager.GetString("ISABIDLink_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISABIDLink.
        /// </summary>
        internal static string ISABIDLink_zh_CN {
            get {
                return ResourceManager.GetString("ISABIDLink_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobID.
        /// </summary>
        internal static string JobID_En {
            get {
                return ResourceManager.GetString("JobID_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作编号.
        /// </summary>
        internal static string JobID_zh_CN {
            get {
                return ResourceManager.GetString("JobID_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line_En {
            get {
                return ResourceManager.GetString("Line_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 折线图.
        /// </summary>
        internal static string Line_zh_CN {
            get {
                return ResourceManager.GetString("Line_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links_En {
            get {
                return ResourceManager.GetString("Links_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接.
        /// </summary>
        internal static string Links_zh_CN {
            get {
                return ResourceManager.GetString("Links_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical.
        /// </summary>
        internal static string Logical_En {
            get {
                return ResourceManager.GetString("Logical_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逻辑.
        /// </summary>
        internal static string Logical_zh_CN {
            get {
                return ResourceManager.GetString("Logical_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupAndReference.
        /// </summary>
        internal static string LookupAndReference_En {
            get {
                return ResourceManager.GetString("LookupAndReference_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找和引用.
        /// </summary>
        internal static string LookupAndReference_zh_CN {
            get {
                return ResourceManager.GetString("LookupAndReference_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins.
        /// </summary>
        internal static string Margins_En {
            get {
                return ResourceManager.GetString("Margins_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页边距.
        /// </summary>
        internal static string Margins_zh_CN {
            get {
                return ResourceManager.GetString("Margins_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MathAndTrigonometry.
        /// </summary>
        internal static string MathAndTrigonometry_En {
            get {
                return ResourceManager.GetString("MathAndTrigonometry_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数学和三角函数.
        /// </summary>
        internal static string MathAndTrigonometry_zh_CN {
            get {
                return ResourceManager.GetString("MathAndTrigonometry_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        internal static string Matrix_En {
            get {
                return ResourceManager.GetString("Matrix_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基质.
        /// </summary>
        internal static string Matrix_zh_CN {
            get {
                return ResourceManager.GetString("Matrix_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Cells.
        /// </summary>
        internal static string Merge_Cells_En {
            get {
                return ResourceManager.GetString("Merge Cells_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并单元格.
        /// </summary>
        internal static string Merge_Cells_zh_CN {
            get {
                return ResourceManager.GetString("Merge Cells_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Method_En {
            get {
                return ResourceManager.GetString("Method_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法依据.
        /// </summary>
        internal static string Method_zh_CN {
            get {
                return ResourceManager.GetString("Method_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode_En {
            get {
                return ResourceManager.GetString("Mode_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模式.
        /// </summary>
        internal static string Mode_zh_CN {
            get {
                return ResourceManager.GetString("Mode_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More_En {
            get {
                return ResourceManager.GetString("More_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他函数.
        /// </summary>
        internal static string More_zh_CN {
            get {
                return ResourceManager.GetString("More_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Calibration.
        /// </summary>
        internal static string NewCalibration_En {
            get {
                return ResourceManager.GetString("NewCalibration_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建标准曲线.
        /// </summary>
        internal static string NewCalibration_zh_CN {
            get {
                return ResourceManager.GetString("NewCalibration_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Comment.
        /// </summary>
        internal static string New_Comment_En {
            get {
                return ResourceManager.GetString("New Comment_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批注.
        /// </summary>
        internal static string New_Comment_zh_CN {
            get {
                return ResourceManager.GetString("New Comment_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number_En {
            get {
                return ResourceManager.GetString("Number_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字.
        /// </summary>
        internal static string Number_zh_CN {
            get {
                return ResourceManager.GetString("Number_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open_En {
            get {
                return ResourceManager.GetString("Open_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        internal static string Open_zh_CN {
            get {
                return ResourceManager.GetString("Open_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string Orientation_En {
            get {
                return ResourceManager.GetString("Orientation_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纸张方向.
        /// </summary>
        internal static string Orientation_zh_CN {
            get {
                return ResourceManager.GetString("Orientation_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他图表.
        /// </summary>
        internal static string Other_Charts_En {
            get {
                return ResourceManager.GetString("Other Charts_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他图表.
        /// </summary>
        internal static string Other_Charts_zh_CN {
            get {
                return ResourceManager.GetString("Other Charts_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageLayout.
        /// </summary>
        internal static string PageLayout_En {
            get {
                return ResourceManager.GetString("PageLayout_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面布局.
        /// </summary>
        internal static string PageLayout_zh_CN {
            get {
                return ResourceManager.GetString("PageLayout_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSetup.
        /// </summary>
        internal static string PageSetup_En {
            get {
                return ResourceManager.GetString("PageSetup_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面设置.
        /// </summary>
        internal static string PageSetup_zh_CN {
            get {
                return ResourceManager.GetString("PageSetup_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste_En {
            get {
                return ResourceManager.GetString("Paste_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        internal static string Paste_zh_CN {
            get {
                return ResourceManager.GetString("Paste_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string Percent_En {
            get {
                return ResourceManager.GetString("Percent_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PercentC.
        /// </summary>
        internal static string Percent_zh_CN {
            get {
                return ResourceManager.GetString("Percent_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string Picture_En {
            get {
                return ResourceManager.GetString("Picture_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片.
        /// </summary>
        internal static string Picture_zh_CN {
            get {
                return ResourceManager.GetString("Picture_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie.
        /// </summary>
        internal static string Pie_En {
            get {
                return ResourceManager.GetString("Pie_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 饼图.
        /// </summary>
        internal static string Pie_zh_CN {
            get {
                return ResourceManager.GetString("Pie_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PivotTable.
        /// </summary>
        internal static string PivotTable_En {
            get {
                return ResourceManager.GetString("PivotTable_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据透视表.
        /// </summary>
        internal static string PivotTable_zh_CN {
            get {
                return ResourceManager.GetString("PivotTable_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print_En {
            get {
                return ResourceManager.GetString("Print_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印.
        /// </summary>
        internal static string Print_zh_CN {
            get {
                return ResourceManager.GetString("Print_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectID.
        /// </summary>
        internal static string ProjectID_En {
            get {
                return ResourceManager.GetString("ProjectID_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目编号.
        /// </summary>
        internal static string ProjectID_zh_CN {
            get {
                return ResourceManager.GetString("ProjectID_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectName.
        /// </summary>
        internal static string ProjectName_En {
            get {
                return ResourceManager.GetString("ProjectName_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCBatchID.
        /// </summary>
        internal static string QCBatchID_En {
            get {
                return ResourceManager.GetString("QCBatchID_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质控批次编号.
        /// </summary>
        internal static string QCBatchID_zh_CN {
            get {
                return ResourceManager.GetString("QCBatchID_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Batch.
        /// </summary>
        internal static string QCBatch_En {
            get {
                return ResourceManager.GetString("QCBatch_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质控批次.
        /// </summary>
        internal static string QCBatch_zh_CN {
            get {
                return ResourceManager.GetString("QCBatch_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadingView.
        /// </summary>
        internal static string ReadingView_En {
            get {
                return ResourceManager.GetString("ReadingView_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阅读视图.
        /// </summary>
        internal static string ReadingView_zh_CN {
            get {
                return ResourceManager.GetString("ReadingView_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadingView.
        /// </summary>
        internal static string Reading_View_En {
            get {
                return ResourceManager.GetString("Reading View_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阅读视图.
        /// </summary>
        internal static string Reading_View_zh_CN {
            get {
                return ResourceManager.GetString("Reading View_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReApply.
        /// </summary>
        internal static string ReApply_En {
            get {
                return ResourceManager.GetString("ReApply_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新应用.
        /// </summary>
        internal static string ReApply_zh_CN {
            get {
                return ResourceManager.GetString("ReApply_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        internal static string Recalculate_En {
            get {
                return ResourceManager.GetString("Recalculate_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新计算.
        /// </summary>
        internal static string Recalculate_zh_CN {
            get {
                return ResourceManager.GetString("Recalculate_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo_En {
            get {
                return ResourceManager.GetString("Redo_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做.
        /// </summary>
        internal static string Redo_zh_CN {
            get {
                return ResourceManager.GetString("Redo_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        internal static string Retrieve_En {
            get {
                return ResourceManager.GetString("Retrieve_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取出.
        /// </summary>
        internal static string Retrieve_zh_CN {
            get {
                return ResourceManager.GetString("Retrieve_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review_En {
            get {
                return ResourceManager.GetString("Review_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证.
        /// </summary>
        internal static string Review_zh_CN {
            get {
                return ResourceManager.GetString("Review_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RollBack.
        /// </summary>
        internal static string RollBack_En {
            get {
                return ResourceManager.GetString("RollBack_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退回.
        /// </summary>
        internal static string RollBack_zh_CN {
            get {
                return ResourceManager.GetString("RollBack_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SaveAs_En {
            get {
                return ResourceManager.GetString("SaveAs_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另存为.
        /// </summary>
        internal static string SaveAs_zh_CN {
            get {
                return ResourceManager.GetString("SaveAs_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save_En {
            get {
                return ResourceManager.GetString("Save_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string Save_zh_CN {
            get {
                return ResourceManager.GetString("Save_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter.
        /// </summary>
        internal static string Scatter_En {
            get {
                return ResourceManager.GetString("Scatter_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分散图.
        /// </summary>
        internal static string Scatter_zh_CN {
            get {
                return ResourceManager.GetString("Scatter_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        internal static string Sheet_En {
            get {
                return ResourceManager.GetString("Sheet_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SheetC.
        /// </summary>
        internal static string Sheet_zh_CN {
            get {
                return ResourceManager.GetString("Sheet_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowHideComment.
        /// </summary>
        internal static string ShowHideComment_En {
            get {
                return ResourceManager.GetString("ShowHideComment_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示/隐藏批注.
        /// </summary>
        internal static string ShowHideComment_zh_CN {
            get {
                return ResourceManager.GetString("ShowHideComment_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show_En {
            get {
                return ResourceManager.GetString("Show_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作表选项.
        /// </summary>
        internal static string Show_zh_CN {
            get {
                return ResourceManager.GetString("Show_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size_En {
            get {
                return ResourceManager.GetString("Size_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纸张大小.
        /// </summary>
        internal static string Size_zh_CN {
            get {
                return ResourceManager.GetString("Size_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortAndFilter.
        /// </summary>
        internal static string SortAndFilter_En {
            get {
                return ResourceManager.GetString("SortAndFilter_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序和筛选.
        /// </summary>
        internal static string SortAndFilter_zh_CN {
            get {
                return ResourceManager.GetString("SortAndFilter_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort A to Z.
        /// </summary>
        internal static string Sort_A_to_Z_En {
            get {
                return ResourceManager.GetString("Sort A to Z_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序 A到Z.
        /// </summary>
        internal static string Sort_A_to_Z_zh_CN {
            get {
                return ResourceManager.GetString("Sort A to Z_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Z to A.
        /// </summary>
        internal static string Sort_Z_to_A_En {
            get {
                return ResourceManager.GetString("Sort Z to A_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序 Z到A.
        /// </summary>
        internal static string Sort_Z_to_A_zh_CN {
            get {
                return ResourceManager.GetString("Sort Z to A_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status_En {
            get {
                return ResourceManager.GetString("Status_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        internal static string Status_zh_CN {
            get {
                return ResourceManager.GetString("Status_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string Styles_En {
            get {
                return ResourceManager.GetString("Styles_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样式.
        /// </summary>
        internal static string Styles_zh_CN {
            get {
                return ResourceManager.GetString("Styles_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table_En {
            get {
                return ResourceManager.GetString("Table_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格.
        /// </summary>
        internal static string Table_zh_CN {
            get {
                return ResourceManager.GetString("Table_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplateName.
        /// </summary>
        internal static string TemplateName_En {
            get {
                return ResourceManager.GetString("TemplateName_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报告模板.
        /// </summary>
        internal static string TemplateName_zh_CN {
            get {
                return ResourceManager.GetString("TemplateName_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string Template_En {
            get {
                return ResourceManager.GetString("Template_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模板.
        /// </summary>
        internal static string Template_zh_CN {
            get {
                return ResourceManager.GetString("Template_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test_En {
            get {
                return ResourceManager.GetString("Test_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监测项目.
        /// </summary>
        internal static string Test_zh_CN {
            get {
                return ResourceManager.GetString("Test_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text_En {
            get {
                return ResourceManager.GetString("Text_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本.
        /// </summary>
        internal static string Text_zh_CN {
            get {
                return ResourceManager.GetString("Text_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools_En {
            get {
                return ResourceManager.GetString("Tools_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具.
        /// </summary>
        internal static string Tools_zh_CN {
            get {
                return ResourceManager.GetString("Tools_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo_En {
            get {
                return ResourceManager.GetString("Undo_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤消.
        /// </summary>
        internal static string Undo_zh_CN {
            get {
                return ResourceManager.GetString("Undo_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update_En {
            get {
                return ResourceManager.GetString("Update_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string Update_zh_CN {
            get {
                return ResourceManager.GetString("Update_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        internal static string UploadImage_En {
            get {
                return ResourceManager.GetString("UploadImage_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传图片.
        /// </summary>
        internal static string UploadImage_zh_CN {
            get {
                return ResourceManager.GetString("UploadImage_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Verify_En {
            get {
                return ResourceManager.GetString("Verify_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批准.
        /// </summary>
        internal static string Verify_zh_CN {
            get {
                return ResourceManager.GetString("Verify_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewToggleEditingView.
        /// </summary>
        internal static string ViewToggleEditingView_En {
            get {
                return ResourceManager.GetString("ViewToggleEditingView_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewToggleEditingViewC.
        /// </summary>
        internal static string ViewToggleEditingView_zh_CN {
            get {
                return ResourceManager.GetString("ViewToggleEditingView_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View_En {
            get {
                return ResourceManager.GetString("View_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        internal static string View_zh_CN {
            get {
                return ResourceManager.GetString("View_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Window_En {
            get {
                return ResourceManager.GetString("Window_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口.
        /// </summary>
        internal static string Window_zh_CN {
            get {
                return ResourceManager.GetString("Window_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Text.
        /// </summary>
        internal static string Wrap_Text_En {
            get {
                return ResourceManager.GetString("Wrap Text_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动换行.
        /// </summary>
        internal static string Wrap_Text_zh_CN {
            get {
                return ResourceManager.GetString("Wrap Text_zh-CN", resourceCulture);
            }
        }
    }
}
