//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tracking {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tracking() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Tracking", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete_En {
            get {
                return ResourceManager.GetString("Complete_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        internal static string Complete_zh_CN {
            get {
                return ResourceManager.GetString("Complete_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionType.
        /// </summary>
        internal static string FunctionType_En {
            get {
                return ResourceManager.GetString("FunctionType_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能节点.
        /// </summary>
        internal static string FunctionType_zh_CN {
            get {
                return ResourceManager.GetString("FunctionType_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indoor Inspection.
        /// </summary>
        internal static string IndoorInspection_En {
            get {
                return ResourceManager.GetString("IndoorInspection_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 室内检验.
        /// </summary>
        internal static string IndoorInspection_zh_CN {
            get {
                return ResourceManager.GetString("IndoorInspection_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_En {
            get {
                return ResourceManager.GetString("Login_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样品登记.
        /// </summary>
        internal static string Login_zh_CN {
            get {
                return ResourceManager.GetString("Login_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Approval.
        /// </summary>
        internal static string PendingApproval_En {
            get {
                return ResourceManager.GetString("PendingApproval_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果批准.
        /// </summary>
        internal static string PendingApproval_zh_CN {
            get {
                return ResourceManager.GetString("PendingApproval_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string PendingEntry_En {
            get {
                return ResourceManager.GetString("PendingEntry_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据分析.
        /// </summary>
        internal static string PendingEntry_zh_CN {
            get {
                return ResourceManager.GetString("PendingEntry_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string PendingReporting_En {
            get {
                return ResourceManager.GetString("PendingReporting_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报告生成.
        /// </summary>
        internal static string PendingReporting_zh_CN {
            get {
                return ResourceManager.GetString("PendingReporting_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDMS Review.
        /// </summary>
        internal static string PendingReview_En {
            get {
                return ResourceManager.GetString("PendingReview_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDMS审核.
        /// </summary>
        internal static string PendingReview_zh_CN {
            get {
                return ResourceManager.GetString("PendingReview_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Validation.
        /// </summary>
        internal static string PendingValidation_En {
            get {
                return ResourceManager.GetString("PendingValidation_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果审核.
        /// </summary>
        internal static string PendingValidation_zh_CN {
            get {
                return ResourceManager.GetString("PendingValidation_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDMS Verify.
        /// </summary>
        internal static string PendingVerify_En {
            get {
                return ResourceManager.GetString("PendingVerify_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDMS批准.
        /// </summary>
        internal static string PendingVerify_zh_CN {
            get {
                return ResourceManager.GetString("PendingVerify_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product and Sample Mapping.
        /// </summary>
        internal static string ProductSampleMapping_En {
            get {
                return ResourceManager.GetString("ProductSampleMapping_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编号匹配.
        /// </summary>
        internal static string ProductSampleMapping_zh_CN {
            get {
                return ResourceManager.GetString("ProductSampleMapping_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Reported_En {
            get {
                return ResourceManager.GetString("Reported_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        internal static string Reported_zh_CN {
            get {
                return ResourceManager.GetString("Reported_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestName.
        /// </summary>
        internal static string TestName_En {
            get {
                return ResourceManager.GetString("TestName_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测项目.
        /// </summary>
        internal static string TestName_zh_CN {
            get {
                return ResourceManager.GetString("TestName_zh-CN", resourceCulture);
            }
        }
    }
}
